// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xumluqpgaipnwopbsswo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1bWx1cXBnYWlwbndvcGJzc3dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNTMyNjAsImV4cCI6MjA1NzkyOTI2MH0.WfD_JQhZr4Q-pAcPETT092Rr86fbT2R2yVE0u3djtX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);